project:
  type: website

website:
  title: "Amanda's Data Science Blog"
  site-url: https://amanda.rbind.io/
  description: "Amanda's Data Science Blog"
  page-navigation: true
  open-graph: true
  twitter-card:
    title: "Amanda's Data Science Blog"
    creator: "@DrAmandaRP"
    card-style: summary
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AmandaRP
      - icon: twitter
        href: https://twitter.com/DrAmandaRP
      - icon: rss
        href: index.xml

format:
  html:
    theme: 
      light: litera
      dark: darkly
    css: styles.css
    toc: true

editor: visual

